---
apiVersion: repo.github.upbound.io/v1alpha1
kind: Repository
metadata:
  name: new-provider-github
spec:
  forProvider:
    visibility: private
    gitignoreTemplate: Terraform
    name: new-provider-github

    # securityAndAnalysis:
    #   - advancedSecurity:
    #     - status: enabled
    #     secretScanning:
    #     - status: disabled
    #     secretScanningPushProtection:
    #     - status: disabled  
  providerConfigRef:
    name: default

