apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: crossplane
  namespace: argocd
spec:
  generators:
  - list:
      elements:
        - appName: crossplane
          repoURL: https://charts.crossplane.io/stable
          chart: crossplane
          namespace: crossplane-system
          targetRevision: 1.18.2
  template:
    # Application Metadata
    metadata:
      name: "{{appName}}-argocd"
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: "{{repoURL}}"
        chart: "{{chart}}"
        helm:
          releaseName: "{{appName}}"
        targetRevision: "{{targetRevision}}"
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true